outprefix: EXPNAME

# raw data location
fastqdir: /path/to/fastq/files/

# sample name for condition 1
sample: sample_name

# sample raw filename prefix for treatment, fastq files in fastqdir should be NAME.fastq.gz
tfileprefix: [cond_treat_rep1, cond_treat_rep2, cond_treat_rep3, cond_treat_rep4]

# sample raw filename prefix for control, fastq files in fastqdir should be NAME.fastq.gz
cfileprefix: [control_rep1, control_rep2, control_rep3, control_rep4]

options:
  # options for the analysis
  # merge controls. If yes, controls for the same condition will be 
  # merged during peak calling; otherwise, treatment and control will
  # be matched. default: Y
  paired: N
  # aligner for mapping reads, choose from minimap2, bwa-mem,
  # bwa-mem2, and chrommap
  # Currently, we only support minimap2 or bwa-mem
  # Choose minimap2 if read is long and speed is a concern
  # Choose bwa-mem for traditional NGS data
  mapper: bwa-mem
  # macs3 related options
  # species: either hs for human or mm for mouse
  # You can also pass the customized effective genome size to it
  # since this is for macs `-g` option only.
  species: hs
  # pvalue or qvalue
  peakcalling_cutoff_method: qvalue
  # cutoff value
  peakcalling_cutoff: 0.05
  # Y to use paried end mode -f BAMPE, otherwise -f BAM. Note: current
  # pipeline only supports BAMPE
  peakcalling_PE_mode: N
  # Y to use --nolambda, otherwise no change
  peakcalling_disable_lambda: N
  # number of cores to use
  cores: 2
  
genome:
  # Genome index for minimap2
  mmi: /path/to/db/genome/GRCh38/genome.mmi
  # Genome index for bwa-mem
  bwaindex: /path/to/db/genome/GRCh38/genome.fa  

annotation:
  # file contains chromosome lengths: 1st col: chromosome name; 2nd
  # col: chromosome length
  chromInfo: /path/to/db/genome/GRCh38/chrom.len
  # BED file for chromosome boundaries: only contain chromosomes you
  # want, for example, excluding chromosome M
  chromBed: /path/to/db/genome/GRCh38/chrom.bed
  # BED file contains promoter regions
  promoter: /path/to/db/genome/GRCh38/GRCh38_promoter.bed
  # BED file contains chrM locations
  MtBed: /path/to/db/genome/GRCh38/GRCh38_chrM.bed
  # BED  file for ENCODE blacklisted regions
  blacklist: /path/to/db/genome/GRCh38/blacklist.bed
  # BED file from Cistrome integrated DNA hypersensitive sites
  DHS: /path/to/db/genome/GRCh38/DHS.bed
  # sqlite3 format database file for CEAS
  CEASlib: /path/to/db/genome/GRCh38/GRCh38.refGene
  # gene annotation in GTF
  geneGTF: /path/to/db/genome/GRCh38/gencode.v22.annotation.gtf
  # GMT files for functional annotation
  GMT: /path/to/db/MSigDB_gmt_files
