outprefix: EXPNAME

# raw data location
fastqdir: /path/to/fastq/files/

# sample names for condition 1, fastq files in fastqdir should be NAME_R1.fastq.gz and NAME_R2.fastq.gz
samples1: [cond1_rep1, cond1_rep2, cond1_rep3, cond1_rep4]
# sample names for condition 2, fastq files in fastqdir should be NAME_R1.fastq.gz and NAME_R2.fastq.gz
samples2: [cond2_rep1, cond2_rep2, cond2_rep3, cond2_rep4]

options:
  # options for the analysis
  # mapping for paired-end or not, choose Y or N
  paired: Y  
  # aligner for mapping reads, choose from minimap2, bwa-mem, bwa-mem2, and chrommap
  mapper: minimap2
  # species
  species: GRCh38
  # pvalue or qvalue
  peakcalling_cutoff_method: qvalue
  # cutoff value
  peakcalling_cutoff: 0.05
  # Y to use paried end mode -f BAMPE, otherwise -f BAM
  peakcalling_PE_mode: Y
  # Y to use --nolambda, otherwise no change
  peakcalling_disable_lambda: Y
  # number of cores to use
  cores: 2
  
genome:
  # Genome index for minimap2
  mmi: /path/to/db/genome/GRCh38/genome.mmi
  # Genome index for bwa-mem
  bwaindex: /path/to/db/genome/GRCh38/genome.fa  

annotation:
  chromInfo: /path/to/db/genome/GRCh38/chrom.len
  chromBed: /path/to/db/genome/GRCh38/chrom.bed
  promoter: /path/to/db/genome/GRCh38/GRCh38_promoter.bed
  MtBed: /path/to/db/genome/GRCh38/GRCh38_chrM.bed
  blacklist: /path/to/db/genome/GRCh38/blacklist.bed
  DHS: /path/to/db/genome/GRCh38/DHS.bed
  CEASlib: /path/to/db/genome/GRCh38/GRCh38.refGene
  geneGTF: /path/to/db/genome/GRCh38/gencode.v22.annotation.gtf



