outprefix: EXPNAME

# raw data location
fastqdir: /path/to/fastq/files/

# sample name for condition 1
sample1: sample_name1

# sample name for condition 2
sample2: sample_name2

# sample raw filename prefix for condition 1, fastq files in fastqdir should be NAME_R1.fastq.gz and NAME_R2.fastq.gz
sample1fileprefix: [cond1_rep1, cond1_rep2, cond1_rep3, cond1_rep4]
# sample raw filename prefix for condition 2, fastq files in fastqdir should be NAME_R1.fastq.gz and NAME_R2.fastq.gz
sample2fileprefix: [cond2_rep1, cond2_rep2, cond2_rep3, cond2_rep4]

options:
  # options for the analysis
  # mapping for paired-end or not, choose Y or N
  paired: Y  
  # aligner for mapping reads, choose from minimap2, bwa-mem,
  # bwa-mem2, and chrommap
  # Currently, we only support minimap2 or bwa-mem
  # Choose minimap2 if read is long and speed is a concern
  # Choose bwa-mem for traditional NGS data
  mapper: bwa-mem
  # macs3 and R analysis related options
  # species: hg18 or hg38 for human or mm10 or mm39 for mouse
  species: hg38
  # pvalue or qvalue
  peakcalling_cutoff_method: qvalue
  # cutoff value
  peakcalling_cutoff: 0.05
  # Y to use paried end mode -f BAMPE, otherwise -f BAM. Note: current
  # pipeline only supports BAMPE
  peakcalling_PE_mode: Y
  # Y to use --nolambda, otherwise no change
  peakcalling_disable_lambda: Y
  # FDR for DAR calling
  dar_fdr: 0.05
  # log2fc for DAR calling
  dar_log2fc: 1
  # DEG file name
  deg_file: NA
  # number of cores to use
  cores: 2
  
genome:
  # Genome index for minimap2
  mmi: /path/to/db/genome/GRCh38/genome.mmi
  # Genome index for bwa-mem
  bwaindex: /path/to/db/genome/GRCh38/genome.fa  

annotation:
  # file contains chromosome lengths: 1st col: chromosome name; 2nd
  # col: chromosome length
  chromInfo: /path/to/db/genome/GRCh38/chrom.len
  # BED file for chromosome boundaries: only contain chromosomes you
  # want, for example, excluding chromosome M
  chromBed: /path/to/db/genome/GRCh38/chrom.bed
  # BED file contains promoter regions
  promoter: /path/to/db/genome/GRCh38/GRCh38_promoter.bed
  # BED file contains chrM locations
  MtBed: /path/to/db/genome/GRCh38/GRCh38_chrM.bed
  # BED  file for ENCODE blacklisted regions
  blacklist: /path/to/db/genome/GRCh38/blacklist.bed
  # BED file from Cistrome integrated DNA hypersensitive sites
  DHS: /path/to/db/genome/GRCh38/DHS.bed
  # sqlite3 format database file for CEAS
  CEASlib: /path/to/db/genome/GRCh38/GRCh38.refGene
  # gene annotation in GTF
  geneGTF: /path/to/db/genome/GRCh38/gencode.v22.annotation.gtf
  # MSigDB path
  MSigDB: /path/to/db/annotation/MSigDB/
  # CistromeDB path (top1k)
  CistromeDB: /path/to/db/giggle/cistromedb/top1k/
  # ENCODE CCRE path
  CCRE: /path/to/db/giggle/ENCODE_CCRE/
